Acme\Bundle\CatalogBundle\Entity\MyProductValue:
    type: entity
    table: acme_catalog_product_value
    indexes:
        value_idx:
            columns:
                - attribute_id
                - locale_code
                - scope_code
        varchar_idx:
            columns:
                - value_string
        integer_idx:
            columns:
                - value_integer
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        varchar:
            type: string
            length: 255
            nullable: true
            column: value_string
        integer:
            type: integer
            nullable: true
            column: value_integer
        decimal:
            type: decimal
            scale: 4
            nullable: true
            precision: 14
            column: value_decimal
        boolean:
            type: boolean
            nullable: true
            column: value_boolean
        text:
            type: text
            nullable: true
            column: value_text
        date:
            type: date
            nullable: true
            column: value_date
        datetime:
            type: datetime
            nullable: true
            column: value_datetime
        locale:
            type: string
            length: 20
            nullable: true
            column: locale_code
        scope:
            type: string
            length: 100
            nullable: true
            column: scope_code
    manyToOne:
        color:
            targetEntity: Acme\Bundle\CatalogBundle\Entity\Color
            cascade:
                - persist
                - refresh
            joinColumns:
                color_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        attribute:
            targetEntity: Akeneo\Pim\Structure\Component\Model\AbstractAttribute
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
        option:
            targetEntity: Akeneo\Pim\Structure\Component\Model\AttributeOption
            cascade:
                - persist
                - refresh
            joinColumns:
                option_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        entity:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\ProductInterface
            inversedBy: values
            joinColumns:
                entity_id:
                    referencedColumnName: id
                    onDelete: CASCADE
    manyToMany:
        options:
            targetEntity: Akeneo\Pim\Structure\Component\Model\AttributeOption
            cascade:
                - refresh
            joinTable:
                name: acme_catalog_product_value_option
                joinColumns:
                    value_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
                inverseJoinColumns:
                    option_id:
                        referencedColumnName: id
                        nullable: true
                        onDelete: CASCADE
    oneToOne:
        media:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductMedia
            cascade:
                - persist
                - refresh
            inversedBy: value
            joinColumns:
                media_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        metric:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\Metric
            cascade:
                - persist
                - refresh
            joinColumns:
                metric_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToMany:
        prices:
            targetEntity: Akeneo\Pim\Enrichment\Component\Product\Model\ProductPrice
            cascade:
                - remove
                - persist
                - refresh
            mappedBy: value
            indexBy: currency
            orderBy:
                currency: ASC
