services:
    acme_notifyconnector.provider.form.job_instance:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
                csv_product_export_notify: pim-job-instance-csv-product-export-notify
        tags:
            - { name: pim_enrich.provider.form }
